[package]
name = "drop-stream"
version = "0.1.0"
edition = "2021"
description = "Get notified when your streams are dropped"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.21"
